version: '3.7'
services:
  web:
    image: "test:dev"
build:
  target: development_build
  context: .
  cache_from:
    - "test:dev"
    - "test:latest"
    - "*"
  args:
    DJANGO_ENV: development
  command: python -Wd manage.py runserver 0.0.0.0:8000
  ports:
    - 8000:8000
  env_file:
    - ./.env.dev
  depends_on:
    - db

  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data
